Revert "Dev"
stepancar-web-programming/2022-fall-lab-portfolio-vu-min-hieu pull request #4
Opened 2022-11-17 08:16 UTC by hieuminhvuu

2022-11-17 08:17 UTC, hieuminhvuu commented
Sorry for merge and close pull request !

2022-11-23 12:11 UTC, hieuminhvuu commented
@stepancar I'm still waitting for u

2022-11-25 04:19 UTC, stepancar commented
@hieuminhvuu , ваш ПР создан не по заданию. По заданию, пр  должен быть из ветки dev в ветку мастер и должен содержать весь добавленный код

2022-11-25 04:19 UTC, stepancar requested changes
ПР создан не по заданию

2022-11-25 21:39 UTC, closed without merging